# Generated by Django 5.0.7 on 2024-07-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_zip_to_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('G', 'GOLD'), ('S', 'SILVER'), ('B', 'BRONZE')], default='G', max_length=1),
        ),
    ]
